ir_datasets_loader
tira-io/tira pull request #292
Opened 2022-11-12 13:59 UTC by simon-reich

Adds ir_datasets_loader.py and ir_datasets_loader_cli.py, which should enable the functionality to load and map datasets data to a standardized format.

2022-11-12 14:15 UTC, mam10eks requested changes
Dear @simon-reich, please find the review, overall, it looks quite good, with only a few minor things that you can improve.

Thans!

2022-11-12 14:15 UTC, mam10eks commented on application/requirements.txt
> -mysql
I guess this was only intended to be temporary on your machine?
Can you please remove this?

2022-11-12 14:15 UTC, mam10eks commented on application/requirements.txt
> -mysqlclient
I guess this was only intended to be temporary on your machine?
Can you please remove this?

2022-11-12 14:15 UTC, mam10eks commented on application/src/tira/ir_datasets_loader.py
> +            "text": doc._asdict(),
The text needs to be a string? Here it is a dictionary.

2022-11-12 14:15 UTC, mam10eks commented on application/src/tira/ir_datasets_loader.py
> +            "query": query._asdict(),
I would suggest that you use the title of the query as long as we do not have the default_text_field.

2022-11-12 14:15 UTC, mam10eks commented on application/src/tira/ir_datasets_loader.py
> +            "text": json.dumps(query._asdict())
I would suggest that you use the title of the query as long as we do not have the default_text_field.

2022-11-13 07:59 UTC, simon-reich commented on application/src/tira/ir_datasets_loader.py
> +            "text": doc._asdict(),
Changed it to json.dumps(doc._asdict()) as in method map_doc.

2022-11-13 08:03 UTC, simon-reich commented on application/src/tira/ir_datasets_loader.py
> +            "text": json.dumps(query._asdict())
Done. Also changed the key to "query", to be consistant with the return of method construct_rerank_row.

2022-11-13 08:03 UTC, simon-reich commented on application/src/tira/ir_datasets_loader.py
> +            "query": query._asdict(),
Done

2022-11-13 08:11 UTC, simon-reich commented on application/requirements.txt
> -mysqlclient
Of cause, sorry. But how do I remove them again? requirements.txt on my machine doesn't have these entries anymore and no changes are registered too, so I don't know where I can change this.

2022-11-13 08:55 UTC, mam10eks requested changes
Please make the small adjustments, (in the requirements.txt), then we can merge this :)

2022-11-13 08:55 UTC, mam10eks commented on application/requirements.txt
> -mysqlclient
You can just add those lines again ;)

2022-11-13 08:55 UTC, mam10eks commented on application/requirements.txt
> -mysqlclient
Please also at the same location, so that this is in the end a no-op.

(Please have a look in the git history if you do not know where they were located.)

2022-11-13 09:40 UTC, simon-reich commented on application/requirements.txt
> -mysqlclient
Alright, I just added them at the same positions and removed them again with another commit afterwards -> like this?

2022-11-13 09:50 UTC, simon-reich commented on application/requirements.txt
> -mysqlclient
Done!

2022-11-13 10:02 UTC, mam10eks approved these changes
Thanks for your adoptions, now everything looks fine!

2022-11-13 10:03 UTC, merged